---
# tasks file for ansible-role-redhat_repo

- name: Install extra packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ redhat_repo_extra_packages }}"

- name: Install repositories
  yum_repository:
    name: "{{ item.key }}"
    description: "{% if 'description' in item.value %}{{ item.value.description }}{% else %}{{ item.key }} repository{% endif %}"
    params: "{{ item.value }}"
  with_dict: "{{ redhat_repo }}"
